script:
  - "make $TEST_SUITE"

language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"

env:
  - TEST_SUITE=test
  - TEST_SUITE=test-harmony

branches:
  only:
    - master
    - dev

matrix:
  fast_finish: true
  include:
    - node_js: "0.12"
      env:
        - TEST_SUITE=test
        - COVERAGE=true
  allow_failures:
    - env:
        - TEST_SUITE=test
        - COVERAGE=true

sudo: false
